version: '3.5'

services:
    redis:
        image: redis
    db:
        image: postgres
        restart: unless-stopped
        environment:
          - POSTGRES_USER=Laurence
          - POSTGRES_PASSWORD=FearTheOldBlood
    frontend:
        image: frontend
        ports:
            - 5000:5000
    backend:
        image: backend
        ports:
            - 8000:8000
        environment:
            - REDIS=redis
            - REDIS_PORT=6379
            - DB_USERNAME=Laurence
            - DB_PASSWORD=FearTheOldBlood
            - DB_HOST=db
        restart: unless-stopped
        depends_on:
            - db
