version: '3.5'

services:
    redis:
        image: redis
    frontend:
        image: frontend
        ports:
            - 5000:5000
    backend:
        image: backend
        ports:
            - 8000:8000
        environment:
            - REDIS=redis
            - REDIS_PORT=6379
        restart: unless-stopped
