version: '3.5'

services:
    redis:
        image: redis
    db:
        image: postgres
        restart: unless-stopped
        environment:
          - POSTGRES_USER=Laurence
          - POSTGRES_PASSWORD=FearTheOldBlood
        volumes:
          - /tmp/data:/var/lib/postgresql/data
    frontend:
        image: frontend
        environment:
            - API_URL=/api/
    backend:
        image: backend
        environment:
            - REDIS=redis
            - REDIS_PORT=6379
            - DB_USERNAME=Laurence
            - DB_PASSWORD=FearTheOldBlood
            - DB_HOST=db
        restart: unless-stopped
        depends_on:
            - db
    nginx:
        image: nginx
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 80:80

