version: '3.5'  

services: 
    front: 
      image: frontend
      ports: 
        - 5000:5000
    back:
      image: backend
      ports: 
        - 8000:8000
      volumes:
        - ./logs.txt:/usr/src/app/logs.txt
